
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nhut
 */
public class StudentGUI extends javax.swing.JFrame {
    private final ArrayList sv = new ArrayList();
    /**
     * Creates new form StudentGUI
     */
    public StudentGUI() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ABC = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtht = new javax.swing.JTextField();
        txtns = new javax.swing.JTextField();
        rNam = new javax.swing.JRadioButton();
        rNu = new javax.swing.JRadioButton();
        txtthem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDS = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Họ tên :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setText("Năm sinh:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel3.setText("Giới tính:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        txtht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthtActionPerformed(evt);
            }
        });
        jPanel1.add(txtht, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 11, 190, -1));
        jPanel1.add(txtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 42, 190, -1));

        ABC.add(rNam);
        rNam.setText("Nam");
        rNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNamActionPerformed(evt);
            }
        });
        jPanel1.add(rNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 69, -1, -1));

        ABC.add(rNu);
        rNu.setText("Nữ");
        rNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNuActionPerformed(evt);
            }
        });
        jPanel1.add(rNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 69, -1, -1));

        txtthem.setText("Thêm");
        txtthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtthemActionPerformed(evt);
            }
        });
        jPanel1.add(txtthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 110, -1, -1));

        jButton2.setText("Nạp vào");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        taDS.setColumns(20);
        taDS.setRows(5);
        jScrollPane1.setViewportView(taDS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 400, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthtActionPerformed

    private void rNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNamActionPerformed

    private void rNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNuActionPerformed

    private void txtthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtthemActionPerformed
        String HoTen = txtht.getText();
        int NamSinh = Integer.parseInt(txtns.getText());
        String GioiTinh = null;
        if(rNam.isSelected())
            GioiTinh = "Nam";
        if(rNu.isSelected())
            GioiTinh = "Nu";
        SinhVien x = new SinhVien();
        x.setHoTen(HoTen);
        x.setGioiTinh(GioiTinh);
        x.setNamSinh(NamSinh);
        sv.add(x);
        JOptionPane.showConfirmDialog(null, "Them Thanh Cong!");
    }//GEN-LAST:event_txtthemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for (Object z:sv)
        {
            String s = new String();
            s = (((SinhVien) z).getHoTen()) + "     " + ((SinhVien) z).getNamSinh() +"    "+((SinhVien) z).getGioiTinh()+"\n";
            taDS.insert(s, 0);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ABC;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rNam;
    private javax.swing.JRadioButton rNu;
    private javax.swing.JTextArea taDS;
    private javax.swing.JTextField txtht;
    private javax.swing.JTextField txtns;
    private javax.swing.JButton txtthem;
    // End of variables declaration//GEN-END:variables
}
